.github/ISSUE_TEMPLATE/config.yml, README.md
=> Fixing reference to cv32e40p

docs/user_manual/requirements.txt
=> Added missing tool reqs file

docs/user_manual/source/control_status_registers.rst
=> Fixed tdata2 mode

docs/user_manual/source/pma.rst
=> Doc upddate. Clarify PMA address matching.

docs/user_manual/source/integration.rst, docs/user_manual/source/intro.rst
=> Added limited bit manipulation support, updated Zce version

rtl/include/cv32e40s_pkg.sv
=> Update MARCHID to 21

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_alu.sv, rtl/cv32e40s_b_decoder.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_m_decoder.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_mpu_sva.sv, sva/cv32e40s_mult_sva.sv
Merged in recent changes from cs32e40x.
=> Cv32e40x merge 210716

sva/cv32e40s_mpu_sva.sv
=> Assertion fixes

sva/cv32e40s_mpu_sva.sv
Reverts openhwgroup/cv32e40s#26
=> Revert "Assertion fixes"

docs/user_manual/source/control_status_registers.rst
=> Changed U bit to 1 in misa CSR

sva/cv32e40s_mpu_sva.sv
Reverts openhwgroup/cv32e40s#27
=> Revert "Revert "Assertion fixes""

docs/user_manual/source/intro.rst
=> Documentation only: OBI link fix

docs/user_manual/source/index.rst, docs/user_manual/source/integration.rst, docs/user_manual/source/intro.rst
=> Documentation only. Synthesis related updates. Fencei related updates

docs/user_manual/source/rvfi.rst
User manual updates for RVFI tracer.
=> Updated user manual for the rvfi tracer

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_rvfi_trace.svh, bhv/cv32e40s_wrapper.sv, bhv/include/cv32e40s_wrapper.vh, reference/beh_lib.sv, reference/el2_exu.sv, reference/el2_exu_alu_ctl.sv, reference/el2_exu_div_ctl.sv, reference/readme.txt, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_mpu.sv, rtl/cv32e40s_pma.sv, rtl/cv32e40s_wb_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_ex_stage_sva.sv, sva/cv32e40s_mpu_sva.sv, sva/cv32e40s_wb_stage_sva.sv
=> Merge e40x to e40s

bhv/cv32e40s_wrapper.sv
=> Connected usermode and pmp CSRs to RVFI

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv
=> PMP CSR renaming + RVFI hookup

bhv/cv32e40s_wrapper.sv, cv32e40s_manifest.flist, rtl/cv32e40s_alert.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_register_file_ecc.sv, rtl/cv32e40s_register_file_wrapper.sv, rtl/include/cv32e40s_pkg.sv
Implemented ECC for the register file, added alert_major_o and alert_minor_o core outputs.
=> Implemented ECC for the register file

rtl/cv32e40s_alert.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv
Added all alert triggers to trig module and connected triggers from the security features that have been implemented.
Tied off the remaining security feature triggers with todos.
=> Added all alert triggers to trig module

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/integration.rst, docs/user_manual/source/register_file.rst
Updated documentation to include handling of logically redundant security features
=> Updated documentation

README.md, docs/user_manual/source/intro.rst, docs/user_manual/source/rvfi.rst
=> Update of spec versions

bhv/cv32e40s_wrapper.sv, constraints/cv32e40s_core.sdc, docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/integration.rst, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_mpu.sv, rtl/cv32e40s_pma.sv, rtl/cv32e40s_wb_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_id_stage_sva.sv
=> Weekly merge

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, cv32e40s_manifest.flist, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_dummy_instr.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_register_file.sv, rtl/cv32e40s_register_file_wrapper.sv, rtl/cv32e40s_wb_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_dummy_instr_sva.sv, sva/cv32e40s_id_stage_sva.sv, sva/cv32e40s_if_stage_sva.sv, sva/cv32e40s_rvfi_sva.sv, sva/cv32e40s_wb_stage_sva.sv
Implemented Dummy Instruction Insertion and added related assertions.
=> Dummy Instruction Insertion

docs/user_manual/source/rvfi.rst
Updated documentation for rvfi_trap
=> Updated documentation for rvfi_trap

bhv/cv32e40s_wrapper.sv, sva/cv32e40s_dummy_instr_sva.sv
Updated dummy instruction assertion to account for rnddummyfreq csr writes. Added never_count_on_overflow assertion
=> Updated dummy instruction assertion

docs/user_manual/source/xsecure.rst
Updated documentation for implemented features in the xsecure chapter.
=> Xsecure doc update

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/xsecure.rst
=> Security related documentation updates

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_lfsr.sv, sva/cv32e40s_dummy_instr_sva.sv
Updated LFSRs to handle writes, lockups and shifts correctly.
Fix for #90 
=> Fixed secureseed register write issue

sva/cv32e40s_controller_fsm_sva.sv
=> Update assertion comment

rtl/cv32e40s_pmp.sv
=> Reorganize PMP to allow more parallelization to ease timing

rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_dummy_instr.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_rvfi_sva.sv
=> Fixed formal warnings, added todo

docs/user_manual/source/integration.rst, docs/user_manual/source/intro.rst
=> Fixed smepmp versions. Added RV32 parameter

bhv/cv32e40s_wrapper.sv, docs/user_manual/source/exceptions_interrupts.rst, docs/user_manual/source/integration.rst, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv
Updated clic interface and added it to intergration doc. Fixed merge issue
=> Updated clic interface

docs/user_manual/source/exceptions_interrupts.rst, docs/user_manual/source/intro.rst, docs/user_manual/source/preface.rst
=> Spec link update. NMI exception code updates

docs/user_manual/source/integration.rst, docs/user_manual/source/xsecure.rst
Updated lfsr configuration parameters.
=> Documentation: Updated lfsr configuration parameter documentation

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, sva/cv32e40s_controller_fsm_sva.sv
=> Flush pipeline upon PMP CSR updates

bhv/cv32e40s_core_log.sv, bhv/cv32e40s_wrapper.sv, constraints/cv32e40s_core.sdc, rtl/cv32e40s_core.sv
=> Added parity signals to core interfaces, removed top level parameters

rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_mpu.sv
In preparation for CLIC and Zc implementation.
The portion of this PR related to PMA will be carried over to e40x once the PR is approved.
=> Update MPU to support data access in instruction side. 

rtl/include/cv32e40s_pkg.sv
=> Removed obsolete bitfields

sva/cv32e40s_core_sva.sv
Updated failing assertions which did not correctly account for user mode.
=> SVA updates: Fixed failing assertions in core_sva

docs/user_manual/source/instruction_fetch.rst, docs/user_manual/source/load_store_unit.rst, docs/user_manual/source/xsecure.rst
=> Described OBI parity and checksum signals

rtl/include/cv32e40s_pkg.sv
Updated interface only (actual functionality has not been implemented yet) (will do documentation PR next)
=> Added integrity bit to PMA

bhv/cv32e40s_rvfi.sv, docs/user_manual/source/rvfi.rst, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_if_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_rvfi_sva.sv
=> Merge from 40x

rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_csr.sv
=> Propagate LIB parameter to stdcell wrappers

docs/user_manual/source/intro.rst
=> Update CLIC version

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, bhv/include/cv32e40s_rvfi_pkg.sv, bhv/include/cv32e40s_wrapper.vh, docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/rvfi.rst, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_rvfi_sva.sv
SEC clean vs previous version of e40s (with SMCLIC=0).
Please have @silabs-halfdan review the merge wrt rvfi.
=> Weekly merge from e40x

rtl/cv32e40s_cs_registers.sv
=> Add missing LIB parameter in CLIC CSR's

rtl/cv32e40s_cs_registers.sv
=> Tie off mie_rd_error when mie CSR is not implemented

rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_pc_check.sv
=> Added use of USE_DEPRECATED_FEATURE_SET in the pc_check module.

bhv/cv32e40s_wrapper.sv, constraints/cv32e40s_core.sdc, rtl/cv32e40s_compressed_decoder.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_pc_check.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_decoder_sva.sv, sva/cv32e40s_rvfi_sva.sv
E40X -> E40S merge.
Some additional fixes after the merge.
SEC clean when SMCLIC=0
=> Silabs oysteink merge16

rtl/cv32e40s_register_file_wrapper.sv
=> Removed parantheses in a cast (flagged as error when using questa)

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_prefetch_unit.sv, rtl/cv32e40s_prefetcher.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_decoder_sva.sv, sva/cv32e40s_prefetch_unit_sva.sv, sva/cv32e40s_prefetcher_sva.sv
Merge from CV32E40X.
SEC clean when SMCLIC==0
=> Silabs oysteink merge w17 1

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_compressed_decoder.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_if_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_decoder_sva.sv
Merge cv32e40x -> cv32e40s.
SEC clean.
=> Silabs oysteink merge w17 2

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_register_file.sv, rtl/cv32e40s_register_file_ecc.sv, sva/cv32e40s_register_file_sva.sv
Inverted every other bit in register ECCs
Added ECC helper assertions to ease execution of to level assertions in formal verification
=> Register file ECC bit inversion

rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv
=> Made mcounteren WARL 0x0

docs/user_manual/source/integration.rst, docs/user_manual/source/pmp.rst
=> Fixed PMP granularity formula

docs/user_manual/source/xsecure.rst
=> Added additional minor alert sources

docs/user_manual/source/control_status_registers.rst
=> Removed random data feature

rtl/include/cv32e40s_pkg.sv
=> Removed unused cpuctrl.rnddata bitfield

bhv/cv32e40s_dbg_helper.sv, bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_b_decoder.sv, rtl/cv32e40s_compressed_decoder.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_id_stage_sva.sv, sva/cv32e40s_register_file_sva.sv
Must be merged _after_ PR #189.
Merging in from CV32E40X. 
This merge includes all the easy Zc* instructions.
SEC clean vs PR #189.
One more merge is expected to make E40S formal clean again.
=> Silabs oysteink merge w18 zc

docs/user_manual/source/xsecure.rst
=> Updated list of Xsecure features

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_alu.sv, rtl/cv32e40s_alu_b_cpop.sv, rtl/cv32e40s_b_decoder.sv, rtl/cv32e40s_clic_int_controller.sv, rtl/cv32e40s_compressed_decoder.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_div.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_instr_obi_interface.sv, rtl/cv32e40s_int_controller.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_lsu_response_filter.sv, rtl/cv32e40s_m_decoder.sv, rtl/cv32e40s_prefetch_unit.sv, rtl/cv32e40s_prefetcher.sv, rtl/cv32e40s_sleep_unit.sv, rtl/cv32e40s_wb_stage.sv, rtl/cv32e40s_write_buffer.sv
Includes large 40X commit for easier diff and the wrapper fix for sys_mret_unqual.
SEC clean.
=> Silabs oysteink merge w19 2

docs/user_manual/source/exceptions_interrupts.rst
=> Reordered content in exceptions and interrupts chapter for clarity

rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, sva/cv32e40s_core_sva.sv
=> Silabs oysteink merge jvt stall

docs/user_manual/source/debug.rst
=> Removed reference to uret

bhv/cv32e40s_rvfi.sv, rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_rvfi_sva.sv
Not SEC clean.
Fixed various CSR hardening issues. Only mstateen0 still needs to be hardened when added.
=> Fixed CSR hardening

rtl/cv32e40s_clic_int_controller.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_cs_registers.sv, sva/cv32e40s_controller_fsm_sva.sv
=> Merge from CV32E40X

rtl/cv32e40s_cs_registers.sv
=> Fix for issue #70

rtl/cv32e40s_cs_registers.sv
SEC clean for default SEC config
Not SEC clean for 0 PMP regions
=> Tied off PMP related signals when PMP not fully configured

rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_if_stage.sv, sva/cv32e40s_ex_stage_sva.sv
SEC clean
Todos for recent self merged PRs
=> Added todos related to recent PRs

bhv/cv32e40s_rvfi.sv
=> RVFI fix for issue 248 (wrong rvfi_dbg)

rtl/cv32e40s_mpu.sv, rtl/cv32e40s_pmp.sv
Should fix https://github.com/openhwgroup/cv32e40s/issues/249
=> PMP fix (issue 249)

rtl/cv32e40s_pmp.sv
=> PMP fix (additional fix for issue 249)

bhv/cv32e40s_rvfi.sv
=> Added reset value for rvfi_mode

docs/user_manual/source/xsecure.rst
=> Added notes on checksum behavior for sub-word transactions

rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv
SEC clean (with and without SMCLIC)
=> Added WARL resolution functions. Minimizing diff with 40X

rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv
Fix for https://github.com/openhwgroup/cv32e40s/issues/196
=> Fix for issue 196

rtl/cv32e40s_pmp.sv
=> Update for readability. SEC clean

rtl/cv32e40s_cs_registers.sv
=> Update WARL behavior of PMPCFG.R/W/X

bhv/cv32e40s_rvfi.sv, rtl/cv32e40s_cs_registers.sv
=> Update for issue #255. Implement pmp_addr_n_r for RVFI.

rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_mpu.sv, rtl/cv32e40s_pma.sv, rtl/include/cv32e40s_pkg.sv
Send PMA integrity bit to the bus interface modules
SEC clean
=> Implement PMA integrity

docs/user_manual/source/control_status_registers.rst
=> Fixed cpuctrl.rnddummyfreq description

bhv/cv32e40s_wrapper.sv, cv32e40s_manifest.flist, rtl/cv32e40s_alert.sv, rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_dummy_instr.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_instr_obi_interface.sv, rtl/cv32e40s_lsu_response_filter.sv, rtl/cv32e40s_obi_integrity_fifo.sv, rtl/cv32e40s_prefetch_unit.sv, rtl/cv32e40s_rchk_check.sv, rtl/include/cv32e40s_pkg.sv
Fixes for additional comments after the first integrity PR was merged.
SEC clean.
=> Fixes for issue #307

README.md
=> Removed reference to unsupported Zcmb extension

rtl/cv32e40s_cs_registers.sv
=> Update PMPnCFG WARL behaviour. Fix for issue #294

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/xsecure.rst
=> Now using c.slli as custom hint instead of slt

rtl/cv32e40s_cs_registers.sv
=> Add missing LIB parameter for CSR

docs/user_manual/source/control_status_registers.rst
=> Add notes about PMPCFG and PMPADDR in user manual

rtl/cv32e40s_load_store_unit.sv
=> Set correct priv level for LSU obi.prot

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_register_file.sv, rtl/cv32e40s_register_file_wrapper.sv, rtl/cv32e40s_sequencer.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_id_stage_sva.sv, sva/cv32e40s_register_file_sva.sv
SEC clean when parameter RV32=RV32I
=> Merge rv32e from e40x

docs/user_manual/source/xsecure.rst
=> Added bus protocol error as source for major alert

bhv/cv32e40s_wrapper.sv, sva/cv32e40s_mpu_sva.sv
=> Update PMP asserts

yaml/csrs.yaml
This is the "original" CSR definitions yaml file that we've had internally.
An up-to-date version will be in a separate PR to make the diff easier to review.
=> add csr definitions yaml

docs/user_manual/source/xsecure.rst
=> And instructions can be inserted as random or dummy instructions

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/xsecure.rst
=> Removed references to no longer existing mclicbase CSR

rtl/cv32e40s_controller_fsm.sv
=> Ebreak exceptions depend on privilege level and dcsr.ebreakm/ebreaku

rtl/cv32e40s_alignment_buffer.sv
Suggested code change is not SEC clean. Commented why.
=> Removed 'todo' and added comments to explain code better.

rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_csr.sv, rtl/cv32e40s_dummy_instr.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_pmp.sv
=> Lint fixes

docs/user_manual/source/pipeline.rst
Merged updated cycle count chapter and updated for cv32e40s.
=> Updated cycle counts in user manual (merge from cv32e40x)

rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_debug_triggers.sv, rtl/cv32e40s_i_decoder.sv, rtl/include/cv32e40s_pkg.sv
=> Parameterize user mode features

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv
This PR replaces https://github.com/openhwgroup/cv32e40s/pull/494
=> Fix bhv todos

rtl/cv32e40s_controller_fsm.sv
=> Removed double check of !csr_flush_ack_q.
