openhwgroup/cv32e40s

bhv/cv32e40s_rvfi.sv, sva/cv32e40s_core_sva.sv
Similar fixes were applied to the CV32E40X
Enables core to run under Questa and DSIM.
=> RVFI fix and SVA perf fix

rtl/cv32e40s_cs_registers.sv
this will enable using the Imperas OVPSIM cv32e40s variant - user mode can not be disabled on the model so we must match the CSR setting
Signed-off-by: Steve Richmond <Steve.Richmond@silabs.com>
=> set MISA bit [20] for user mode supported

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_id_stage.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_ex_stage_sva.sv, sva/cv32e40s_id_stage_sva.sv
mret during user mode will result in illegal instruction.
WFI during user mode will result in illegal instruction if mstatus.tw == 1.
Added stalling of IF stage if WFI is present and CSR writes (including priv lvl updates via mret) is present in EX or WB.
=> mret and wfi in User mode

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_dummy_instr.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_register_file.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_dummy_instr_sva.sv, sva/cv32e40s_id_stage_sva.sv
Addressed issues pointed out in #92  :
- Updated dummy instruction assertions to not have special case around writes.
- Updated dummy instruction insertion counter to reset when insertion frequency controls are updated.
- Made dummy instruction part of register file support REGFILE_NUM_WRITE_PORTS
=> Dummy instruction fixes

rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv
Combine cpuctrl_wr_in_wb and secureseed_wr_in_wb into xsecure_csr_wr_in_wb.
Make xsecure_csr_wr_in_wb independent of control signals from FSM to ease timing.
SEC clean
=> Timing fix

bhv/cv32e40s_sim_sffr.sv, bhv/cv32e40s_sim_sffs.sv, cv32e40s_manifest.flist, docs/user_manual/source/getting_started.rst, docs/user_manual/source/xsecure.rst, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_csr.sv, rtl/include/cv32e40s_pkg.sv
Instantiated shadow flops for csr hardening to avoid them being optimized away.
=> Instantiated shadow flops for csr hardening

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_wb_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_id_stage_sva.sv
Jumps (including mret) and branches are now treated as multi cycle / multi operation instructions.
These instructions will now spend two cycles in ID, EX and WB.
A 'last_op' bit has been added to the id_ex_pipe and ex_wb_pipe, this bit will be low for the
first cycle of jumps and branhces, and high for the second cycle and any other instructions.
wb_valid will only go high for instructions with last_op=1.
- Passes ci_check.
- Not SEC clean.
-- Non-taken branches gets one cycle extra penalty
-- Jumps will get different stall conditions making it non-SEC
=> Precursor to PC hardening, multi cycle jumps and branches

rtl/cv32e40s_controller_fsm.sv
After adding the pipeline PC mux, xsecure CSR updates cause a jump to wb.pc (not wb.pc + 4).
Adding logic to control the PC mux.
=> Fix bug where xsecure csr update would cause circular jumps

rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv
Fix type for parameter PMP_PMPADDR_RV and width of reset value used for pmp_addr_csr_i
=> PMP_PMPADDR_RV fix

bhv/cv32e40s_wrapper.sv, docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/exceptions_interrupts.rst, docs/user_manual/source/integration.rst, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_pc_check.sv, rtl/include/cv32e40s_pkg.sv
Plus an additional bugfix where the pc_check module was not updated with regards to changes in mtvec alignment.
=> Merge from E40X til E40S

rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_pc_check.sv
Updates to pc_check module to exlucde CLIC pointer fetches for address comparisons.
=> pc_check updates for CLIC pointers.

rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_load_store_unit.sv, sva/cv32e40s_controller_fsm_sva.sv
All design assertions now pass with both SMCLIC=0 and SMCLIC=1. The only exception are pc_check related assertions which is very hard to converge, not failing after approximately two hours though.
=> Updates after running formal

bhv/cv32e40s_dbg_helper.sv, bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_decoder.sv, rtl/cv32e40s_id_stage.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_id_stage_sva.sv, sva/cv32e40s_register_file_sva.sv
Partly merge from CV32E40X.
Merged at the point where jumps and mrets were no longer qualified with alu_en/sys_en in the controller. This change breaks the E40S' handling of privilege level. Further merge PRs will come after this one to get in sync with CV32E40X and fix the issue with unqualified jumps and mrets.
Not SEC clean
=> Silabs oysteink merge w18

bhv/cv32e40s_wrapper.sv, docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/load_store_unit.rst, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_id_stage.sv, sva/cv32e40s_core_sva.sv
Merge from X, taking in reverted controller logic for jumps and mrets.
Small update to self_stall logic for mrets and jumps, and added assertions to check that using qualified or unqualified signals from ID stage when checking for self_stall is equivalent.
=> Silabs oysteink w18 m3

bhv/cv32e40s_rvfi.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/include/cv32e40s_pkg.sv
Not SEC clean
Removed dedicated hardware performance counter events
Removed Zihpm and Zicntr 
NUM_MHPMCOUNTERS = 0 (mhpmcounter3-31 will be WARL 0)
RVFI needed to be hacked to work around issue in its code that needs to be fixed on the CV32E40X first. Due to this RVFI issue RVFI will still report value for the user mode aliases.
=> Reduced profiling infrastructure. Removed support for Zihpm and Zicntr

rtl/cv32e40s_cs_registers.sv
=> Tied off CLIC CSR rd_error signals when SMCLIC=0.

docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/fencei.rst
Added fence.i related notes. Added mstateen CSRs (applicable to CV32E40S, not to CV32E40X)
=> Cherry picked commit for addition of Smstateen CSRs from CV32E40X.

bhv/cv32e40s_wrapper.sv, cv32e40s_manifest.flist, docs/user_manual/source/control_status_registers.rst, docs/user_manual/source/debug.rst, docs/user_manual/source/pma.rst, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_sequencer.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_if_stage_sva.sv, sva/cv32e40s_sequencer_sva.sv
Includes the new Zc sequencer.
SEC clean when ZC_EXT=1.
There are known failing assertions when ZC_EXT=1. These will be fixed once the sequencer is fully operational and merged in from CV32E40X.
=> Merge from CV32E40X

bhv/rvfi_sim_trace.sv
Simulation performance profiling shows that the itrace module currently exhibits excessive resource usage, added parameter to selectively enable this feature if needed (disabled by default).
(Example: Identical run of corev_rand_instr_test with xcelium had its run time reduced from several hours to 2 minutes when this module was disabled)
Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>
=> Added parameter to disable itrace

rtl/cv32e40s_cs_registers.sv
Update to set rvfi_wmask on ignored writes to PMP CSRs'.
SEC clean
=> Fix pmp csr rvfi

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_prefetch_unit.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_prefetch_unit_sva.sv
This merge introduces a bug related to CLIC pointer fetch while MRET in WB. This bug will be fixed on cv32e40x and merged over to cv32e40s
=> Merge from e40x

bhv/cv32e40s_wrapper.sv, cv32e40s_manifest.flist, rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_cs_registers.sv, rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_dummy_instr.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_instr_obi_interface.sv, rtl/cv32e40s_prefetch_unit.sv, rtl/cv32e40s_rchk_check.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_instr_obi_interface_sva.sv
Instruction OBI parity for gnt and rvalid checked in instruction OBI interface. If a parity fault occurs here, alert_major_o will go high when not in reset. 
Checking instr_rchk_i in the instruction OBI interface when rvalid=1, PMA.integrity=1 and the cpuctrl.integrity bit is set. Fans into alert_major_o. Alignment buffer checks two RCHK checksums, once for each buffer entry that may be used when assembling instructions  (plus the error bit from the obi interface rchk).
Any detected parity or rchk fault within the alignment buffer is a source for alert_major_o. In addition, such faults will travel with the instruction(s) affected and raise exceptions once in WB. 
Both instruction and LSU achk updated to match user manual 0.5.0.
PR includes turning on cpuctrl.integrity, …
=> Instruction side integrity check

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_instr_obi_interface.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_lsu_response_filter.sv, rtl/cv32e40s_rchk_check.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_data_obi_interface_sva.sv, sva/cv32e40s_rvfi_sva.sv
LSU will signal intergrity_err_o (fans into alert_major_o) immediately when any parity error on data_gnt_i or data_rvalid_i is detected. Similarly for errors on data_rchk_i, an integrity_err_o will be flagged if cpuctrl.integrity is set and the transaction is from a PMA region with integrity enabled.
Any load or store with integrity errors as described above will generate an NMI.
=> Added LSU integrity checking.

rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_instr_obi_interface.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_lsu_response_filter.sv, rtl/cv32e40s_obi_integrity_fifo.sv
Added separate counter for outstanding transaction in data_obi_interface.
The counter previously used (from the lsu_respnse_filter) cannot be used in the case where a transfer happens for a region with both integrity and bufferable set. Then the outstanding counter can be manipulated by the write_buffer - thus the obi interface needs it own counter to know the state of the bus outside of the write buffer.
=> Added separate OBI data interface counter for outstanding transaction.

rtl/cv32e40s_alert.sv, rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_instr_obi_interface.sv, rtl/cv32e40s_load_store_unit.sv, rtl/cv32e40s_lsu_response_filter.sv, rtl/cv32e40s_obi_integrity_fifo.sv, rtl/cv32e40s_prefetch_unit.sv, sva/cv32e40s_core_sva.sv
Added OBI protocol hardening. A major alert will be flagged if any OBI interface receive an _rvalid when the outstanding counter is zero. A similar check is performed in the LSU on the inside of the MPU, also resulting in alert_major if the MPU sends a valid response when the outstanding counter int he LSU is zero.
Not SEC clean as this fans into changes in alert_major_o.
=> OBI protocol hardening

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_dummy_instr.sv, sva/cv32e40s_dummy_instr_sva.sv
A dummy instruction which is not yet accepted by the id_stage shall not reset the counter that tracks number of issued instructions.
=> Fix for issue #293. 

rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_cs_registers.sv, sva/cv32e40s_controller_fsm_sva.sv, sva/cv32e40s_cs_registers_sva.sv
Updated handling of mret related to mcause.mpp and mcause.minhv. No inhv assumes for mpp==PRIV_LVL_U. Unique case violation in cs_registers due to clearing of minhv fixed, assertions added to make sure there is no conflicting writes to mcause.
When merged, this PR will be cherry picked to the E40X to apply the changes there. Should fix issue #498 on CV32E40X when done.
=> Updates to mret/xinhv handling.

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller_bypass.sv, rtl/cv32e40s_ex_stage.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/include/cv32e40s_pkg.sv, sva/cv32e40s_controller_fsm_sva.sv
Using last_sec_op instead of last_op when detecting mret_self_stall in controller bypass. Update done because an mret which restarts pointer fetch will not signal last_op until the pointer arrives. Using last_op when checking for mret_self_stall will then not be correct.
Not setting instr_meta.tbljmp for dummy instructions.
=> Fixes after merging from CV32E40X

bhv/cv32e40s_core_log.sv, bhv/cv32e40s_wrapper.sv
Parameterized core_log to enable us to turn off prints from core code in testbenches
Signed-off-by: Henrik Fegran <Henrik.Fegran@silabs.com>
=> Parameterized core_log

rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_csr.sv, rtl/include/cv32e40s_pkg.sv
Updated WARL resolve functions to match supported values by e40s.
Added support for entering debug on ebreak during user mode when dcsr.ebreaku is set.
=> WARL resolve updates and ebreak debug entry for user mode.

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_rvfi_instr_obi.sv, bhv/cv32e40s_wrapper.sv, bhv/include/cv32e40s_rvfi_pkg.sv
Fix for https://github.com/openhwgroup/cv32e40s/issues/333
This update has been verified formally by asserting that we signal PMP error on rvfi_trap.cause_type if and only if we have a instruction access fault. Since PMA can also give instruction access fault, PMA had to be disabled to get the assertions to pass. Because of this, the assertions used to verify this are not checked in.
=> Signal instruction PMP error on RVFI

docs/user_manual/source/control_status_registers.rst
Updated user manual with restricting accesses to the secureseed* CSRs. Only CSRRW with rs1!=x0 will be allowed.
=> Secureseed* updates to user manual.

rtl/cv32e40s_i_decoder.sv
=> Restricting CSR access to SECURESEED* to only CSRRW with rs1!=x0.

yaml/csr.yaml.m4
This PR merges the CSR Yaml fixes that were made on 40s into the 40x CSR Yaml.
The result is 1 CSR Yaml file that is common for both cores with conditionals separating the differences.
PR'ing to the 40s repo as the diff is smaller here (PR to 40x would contain the previous updates in addition).
=> Merge x/s csr yaml with m4 conditionals

bhv/cv32e40s_wrapper.sv, sva/cv32e40s_cs_registers_sva.sv
Added assertions to check that set/clear with rs1==0 will not change any bits in the following CSRs:
mstateen0
cputrl
mseccfg
pmpaddr0-63
pmpcfg0-15
Note that the assertion checking pmpaddr0-63 fails. An issue will be created for this.
=> Assertions for CSR set/clear with rs1==0

rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_id_stage.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_pc_check.sv, rtl/cv32e40s_pc_target.sv, sva/cv32e40s_id_stage_sva.sv
Implemented turning pc_hardening on and off by using cpuctrl.pc_hardening.
Includes the following bugfixes:
- For a pipeline flush due to CSR writes, the controller could kill the pipeline for debug or interrupts before the flush was completed.
- The id_ex_pipe.pc_next was wrong for dummy branches (should have been +0 instead of +4)
=> Implement turning on and off PC hardening.

rtl/cv32e40s_csr.sv
Refactored CSR code when SHADOWCOPY==0. If a CSR bit was 1 in the reset value while the corresponding mask bit was 0 the resulting bit in the CSR would be 0.
SEC clean when turning off shadowcopy in the impl and not the spec.
=> Partial fix for X-issue #766

rtl/cv32e40s_cs_registers.sv
Added shadowcopy to mcause for both CLIC and CLINT.
Hooked up mcause_rd_error.
SEC clean.
=> Fix for issue #116

rtl/cv32e40s_controller_fsm.sv
Removed the check for debug mode when setting ctrl_fsm_o.jump_in_id_raw. This is not needed as an mret will never assert sys_mret_id while in debug mode anymore. Signal does not exist on cv32e40x.
SEC clean.
=> Small update according to issue #458 on cv32e40x.

rtl/cv32e40s_controller_fsm.sv, sva/cv32e40s_if_stage_sva.sv
Updated assertion to chekc that we don't issue dummies back-to-backc without regular instructions in between.
=> Removed todo in controller related to dummies and forward progress.

rtl/cv32e40s_dummy_instr.sv
Converted unique case to regular case with default to avoid warning during simulation.
SEC clean.
=> Fix for issue #596 on cv32e40x.

bhv/cv32e40s_rvfi.sv, bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_controller.sv, rtl/cv32e40s_controller_fsm.sv, rtl/cv32e40s_core.sv, rtl/cv32e40s_dummy_instr.sv, rtl/cv32e40s_if_stage.sv, sva/cv32e40s_dummy_instr_sva.sv, sva/cv32e40s_if_stage_sva.sv
- Changed when the counter for issued instructions are reset.
- Some logic that was used to reset counters (through ctrl_fsm.allow_dummy_instr) was instead moved to factor into dummy_insert_o without resetting the counter)
- Changed how we count instructions (counting when the first operation of an instruction goes from IF to ID, excluding pointers)
=> Fix for issue #456

bhv/cv32e40s_rvfi.sv, sva/cv32e40s_rvfi_sva.sv
Fixed issue where rvfi_intr.intr could be set without rvfi_intr.interrupt or rvfi_intr.exception bits set. This would happen when a dummy replaced the first instruction of an interrupt or exception handler.
=> Fix for missing rvfi_intr.interrupt/exception

bhv/cv32e40s_wrapper.sv
This is the same as inside cs_registers. Done to avoid hierarchical references to localparam which some tools does not like.
=> Added localparam for PMP_ADDR_WIDTH within cv32e40s_wrapper. 

rtl/cv32e40s_instr_obi_interface.sv, sva/cv32e40s_alignment_buffer_sva.sv, sva/cv32e40s_core_sva.sv, sva/cv32e40s_instr_obi_interface_sva.sv
In addition to the reported issue this bug could also cause false major alerts.
Integrity fifo in instruction obi used signals with wrong timing. Used trans_i.integrity instead of the actual signals used with req-timing.
=> Fix for issue #473. 

sva/cv32e40s_div_sva.sv
Assertion passing.
Corresponding assertion in e40x will be removed (since e40xdoes not support data independent timing).
=> Uncomment assertion in cv32e40s_div_sva

rtl/cv32e40s_pc_check.sv
Removed todo about stretching PC checks until an IF->ID  transition happens.
Considered too complex at the moment, and the amount of extra hardening is unclear (very dependent on instruction fetch latency).
=> Removed todo about stretching PC checks

rtl/cv32e40s_data_obi_interface.sv, rtl/cv32e40s_debug_triggers.sv, rtl/cv32e40s_i_decoder.sv, rtl/cv32e40s_instr_obi_interface.sv
LEC clean with SECURE=1.
With SECURE=0 and some (to be analyzed) changes in the controller and hacked marchid, this is also LEC clean against the equivalent configuration of CV32E40X.
=> Parameterized SECURE features

rtl/cv32e40s_alignment_buffer.sv, rtl/cv32e40s_if_stage.sv, rtl/cv32e40s_prefetch_unit.sv
- Removed IF stage todo about checking prot bits - already covered by core-v-verif.
- Added localparam to set max number of outstanding transactions in the prefetcher. The only supported value is 2 for now.
SEC clean.
=> IF stage todo removal

bhv/cv32e40s_wrapper.sv, rtl/cv32e40s_cs_registers.sv, sva/cv32e40s_sequencer_sva.sv
Not a real requirement, as the hazard is resolved as a byproduct og other stalls but it is much easier to understand.
=> Flushing pipeline on writes to mstateen0.

rtl/cv32e40s_controller_bypass.sv
Only detecting for WFI/WFE if USER is enabled.
SEC clean when USER==1.
=> Parametrized detection of implicit CSR reads in the ID stage.

sva/cv32e40s_parameter_sva.sv
A fix to the params_sva was missed during the last merge.
=> Cherry picked assertion fix from cv32e40x

rtl/cv32e40s_dummy_instr.sv
=> Tied off undriven pins 'integrity' and 'rchk' in the dummy module.
